### ISSUE TITLE
The default/only third person camera is very hard to use

### ISSUE THREAD

**Issue by finnbear** [AGoblinKing/goblin-life-content#2]
I would suggest switching to a first-person style camera, or one that atleast rotates with the player.

**Comment by AGoblinKing** [comment]
I use to have a fps camera if you toggled off iso but I'm leaving it for the VR patch.

**Comment by AGoblinKing** [comment]
Updated https://goblin.life with zoom controls in FPS mode you can mouse wheel in/out and even zoom beyond FPS
