### ISSUE TITLE
Bridging Bifrost:====

### ISSUE THREAD

**Issue by CamelCam** [AGoblinKing/goblin-life-content#26]
The game is currently in an unplayable state. Scrolling text saying "Bridging Bifrost:========" is displayed on the screen and when joining a world, this is shown;
![unknown](https://user-images.githubusercontent.com/80987073/199146197-fca1b6e8-b3d9-4a52-92e1-9b387455d2b9.png)

**Comment by AGoblinKing** [comment]
Should be fixed, server crashes but reboots now.
