### ISSUE TITLE
High movement latency

### ISSUE THREAD

**Issue by finnbear** [AGoblinKing/goblin-life-content#3]
Player movement starts and stops after the corresponding key is pressed.

**Comment by AGoblinKing** [comment]
You're sending instructions to a puppet server side and only starting/ending your move once the server has accepted these and gotten back to you. This guarantees what you see is accurate even if at the cost of latency. The server is also 250ms tick.

**Comment by finnbear** [comment]
Server round-trip time explains the issue but it doesn't make it any better. This still should be fixed. One way is to implement client side prediction.

**Comment by AGoblinKing** [comment]
Client side prediction is not consistent

**Comment by finnbear** [comment]
That's where interpolation comes in. If the client is off from where the server says it should be, it should interpolate.

**Comment by AGoblinKing** [comment]
Unless they made an illegal move and need to revoke their action. I find the rollbacks too jarring and would rather have consistency    over availability.
